Implemented the share feature (#11)
thisisamank/resizrr pull request #12
Opened 2021-10-13 16:03 UTC by ShivamMenda

Also changed the Colour Picker version because it was giving a warning of Decraparation.

2021-10-13 16:05 UTC, ShivamMenda commented
@thisisamank I have implemented the share feature. Please do a review and let me know if there are any errors. Waiting for your feedback and validation. Thank you.

2021-10-14 07:20 UTC, thisisamank requested changes

2021-10-14 07:20 UTC, thisisamank commented on lib/view_models/select_image/image_view_model.dart
> +    Uint8List pngBytes = byteData!.buffer.asUint8List();
This code is repeated, may be refactor the previous `_convertImageToWidget()` to `_convertImageToBytes()` and return `Uint8List` from it. Use it in the `saveImage` method. Then use the same method for `takePicture()`  method. That would be a cleaner way to do this I guess.

2021-10-14 07:20 UTC, thisisamank commented on lib/view_models/select_image/image_view_model.dart
> +  final GlobalKey genKey = GlobalKey();
What is the use of this?

2021-10-14 10:10 UTC, ShivamMenda commented on lib/view_models/select_image/image_view_model.dart
> +    Uint8List pngBytes = byteData!.buffer.asUint8List();
Okay, will try using refactoring.

2021-10-14 10:10 UTC, ShivamMenda commented on lib/view_models/select_image/image_view_model.dart
> +  final GlobalKey genKey = GlobalKey();
Oh yeah, I was trying some approach from a tutorial, It didn't work so i'll remove this.

2021-10-14 10:46 UTC, ShivamMenda commented
@thisisamank I have refactored the code. Please do check it out. Thanks.

2021-10-14 21:07 UTC, thisisamank approved these changes
Thanks a lot for your contribution! There were a few minor tweaks required which I did. There are a few bugs on master branch so once I resolve them I will merge your PR.

2021-10-15 04:23 UTC, ShivamMenda commented
Okay @thisisamank Sure. Thank you.

2021-10-16 20:32 UTC, merged

2021-10-16 21:52 UTC, thisisamank commented
Hey @ShivamMenda There are a few issues at my side. My master branch was bit messed up so I had to move to last stable version.
I'm sure you must be having the code. Can you make a fresh PR with your changes? 
Really sorry for the trouble.

2021-10-17 04:12 UTC, ShivamMenda commented
Hey @thisisamank Let me check about it and get back to you. I'll make a fresh PR with my changes.

2021-10-19 14:36 UTC, thisisamank commented
Hey @ShivamMenda were you able to check it? You can also copy relevant code (skip the code related to dark mode commits) from here and make a fresh commit to the original repo. Only reason I didn't do it because the commit will have me as author and you have worked on this issue so that's why ;)

2021-10-19 14:38 UTC, ShivamMenda commented
Hey @thisisamank will this affect my hacktoberfest PR's as I open another pull request? I was also thinking if copy pasting from here only

2021-10-19 14:40 UTC, ShivamMenda commented
@thisisamank if this doesn't affect my PR's and contributions towards hacktoberfest I'll open a fresh PR.

2021-10-19 14:47 UTC, ShivamMenda commented
@thisisamank Actually you can only make the commits if you want to. Anyway my PR is merged so it will count as a contribution.

2021-10-19 15:08 UTC, thisisamank commented
No no, it's completely fine. 2 PRs will be counted.

On Tue, Oct 19, 2021, 8:17 PM Shivam Menda ***@***.***> wrote:

> @thisisamank <https://github.com/thisisamank> Actually you can only make
> the commits if you want to. Anyway my PR is merged so it will count as a
> contribution.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/thisisamank/resizrr/pull/12#issuecomment-946800406>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AII4GG3QOWYIWOPNSY6GMOTUHWAH5ANCNFSM5F5SAGOA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-19 16:53 UTC, ShivamMenda commented
@thisisamank okay will open a fresh PR tommorow with the changes.

2021-10-21 11:49 UTC, ShivamMenda commented
@thisisamank I'm so sorry for the delay but there has been something wrong with my laptop and it has gone for service and it will take a while before it comes back. I think it's best you only do the commits from this PR. I'm not sure when the laptop would come back. So it's better that you only commit off the changes. Sorry again.